### ISSUE TITLE
Removing ignored files is too destructive (and causes an error)

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/gscan#43]
This refs: https://github.com/TryGhost/gscan/pull/42

The action taken by gscan here is unfortunately too destructive. 

CASE: I'm developing a theme locally on my machine with Ghost. I use git and some grunt modules to build my theme.

Every time Ghost starts, it will attempt to remove my `.git` folder and my `node_modules`. 

Also, when attempting to delete a `.git` folder, Ghost throws the error:

```
Error: EPERM: operation not permitted, unlink '/Users/hannah/Ghost/Ghost/content/themes/Blog/.git'
    at Error (native)
From previous event:
    at /Users/hannah/Ghost/Ghost/node_modules/gscan/lib/read-theme.js:39:28
    at processImmediate [as _immediateCallback] (timers.js:396:17)
From previous event:
    at /Users/hannah/Ghost/Ghost/node_modules/gscan/lib/read-theme.js:25:24
    at go$readdir$cb (/Users/hannah/Ghost/Ghost/node_modules/graceful-fs/graceful-fs.js:149:14)
    at FSReqWrap.oncomplete (fs.js:82:15)
From previous event:
    at readThemeFiles (/Users/hannah/Ghost/Ghost/node_modules/gscan/lib/read-theme.js:24:35)
    at readTheme (/Users/hannah/Ghost/Ghost/node_modules/gscan/lib/read-theme.js:110:12)
    at Object.checkAll [as check] (/Users/hannah/Ghost/Ghost/node_modules/gscan/lib/checker.js:19:12)
    at Object.checkTheme [as check] (/Users/hannah/Ghost/Ghost/core/server/themes/validate.js:14:30)
    at validateTheme (/Users/hannah/Ghost/Ghost/core/server/api/themes.js:57:44)
```

Steps to reproduce this error:

1. `cd content/themes`
2. `git clone git@github.com:TryGhost/Blog.git`
3. Start Ghost
4. Try to activate the new theme.

--- 

## Resolution

The underlying reason for removing these files is that if they are used to create symlinks that they can do harm. 

However this fix removes the files regardless of whether or not they are symlinks, and doesn't account for if another not-ignored file is used to create a symlink. E.g. index.hbs or the /assets directory.

Equally, whilst doing development, it's perfectly legitimate to have the node_modules folder contain symlinks.

Therefore I think there needs to be some sort of differentiation between the zip preparation and handling a local folder and perhaps between development and production mode?

**Comment by kirrg001** [comment]
https://github.com/TryGhost/gscan/pull/44/files#diff-f42ea9071ddc88664a4253f45006c330R44

Reopen, because `removeFile` can't be used if one of the ignored files is a directory.
