### ISSUE TITLE
Example theme result output fails to render

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/gscan#61]
When trying to use the route `/example/` which is supposed to render `/test/fixtures/example-output.json`, you see an error instead:

```
Unhandled rejection TypeError: Cannot read property 'level' of undefined
    at /Users/aileennowak/Code/gscan/lib/format.js:68:19
    at arrayEach (/Users/aileennowak/Code/gscan/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/Users/aileennowak/Code/gscan/node_modules/lodash/index.js:3345:13)
    at Object.format (/Users/aileennowak/Code/gscan/lib/format.js:65:7)
    at /Users/aileennowak/Code/gscan/app/index.js:41:37
    at tryCatcher (/Users/aileennowak/Code/gscan/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/aileennowak/Code/gscan/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/aileennowak/Code/gscan/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/aileennowak/Code/gscan/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/aileennowak/Code/gscan/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/aileennowak/Code/gscan/node_modules/bluebird/js/release/promise.js:636:18)
    at /Users/aileennowak/Code/gscan/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/aileennowak/Code/gscan/node_modules/jsonfile/index.js:46:5
    at /Users/aileennowak/Code/gscan/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

---

I assume we either need to overhaul the `example-output.json` file or kill the route in general? Is it actually even used somewhere?

**Comment by kirrg001** [comment]
Could you please add steps to reproduce? Thanks 👋

**Comment by AileenCGN** [comment]
Just using the `/example` route does it.  Either on `http://gscan.ghost.org/example` or locally when in develop mode.

**Comment by ErisDS** [comment]
Can't reproduce but we don't need this route
